apiVersion: apps/v1
kind: Deployment
metadata:
  name: nhdy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nhdy
  template:
    metadata:
      labels:
        app: nhdy
    spec:
      containers:
      - image: okteto.dev/nhdy:latest
        name: nhdy
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "10d727b0-0bbe-11ed-861d-0242ac120002"
        - name: Vless_Path
          value: "/vlbg6tfg"
        - name: Vmess_UUID
          value: "10d727b0-0bbe-11ed-861d-0242ac120002"
        - name: Vmess_Path
          value: "/vmj7rgy"
        - name: Share_Path
          value: "/v2link"
